### ISSUE TITLE
cannot pull gitlab package

### ISSUE THREAD

**Issue by KielChan** [storyicon/gos#1]
the error shows like:
```
DEBUG dmake.build(231) 2019-06-12 18:29:39,620 compile: go: gitlab.com/xxxx/xxx@v0.0.0-yyyyy-yyyyy: unexpected status (http://127.0.0.1:41719/gitlab.com/xxx/xxx/@v/v0.0.0-yyyyy-yyyyy.info): 500 Internal Server Error
```
### how to build it
0. in golang v1.12.4
1. git checkout v1.1.0
2. GOOS=linux GOARCH=amd64 CGO_ENABLED=0 GO111MODULE=on  go build

### how to exec it
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 GO111MODULE=on ./gos install -race -v

### go env
in image golang:v1.12.1

### go version
v1.12.1

**Comment by storyicon** [comment]
Thank you for your feedback, I have the following：
1. In gos, go module is always open, so you don't need to open it through `GO111MODULE=on`
2. If you mentioned above is a `private` repository:
    ① Make sure you have its permission.  
    ② Make sure that when you pull it from the command line using `git clone` or `go get`, you don't need to enter username and password on the `interactive command line`.
3. If it's a `public` repository, you can provide its address if it doesn't involve privacy. We'll try to reproduce and fix the error.

**Comment by KielChan** [comment]
> Thank you for your feedback, I have the following：
> 
> 1. In gos, go module is always open, so you don't need to open it through `GO111MODULE=on`
> 2. If you mentioned above is a `private` repository:
>    ① Make sure you have its permission.
>    ② Make sure that when you pull it from the command line using `git clone` or `go get`, you don't need to enter username and password on the `interactive command line`.
> 3. If it's a `public` repository, you can provide its address if it doesn't involve privacy. We'll try to reproduce and fix the error.

1. I can git clone the private repo without any username or password.
2. And the error is the same as before

**Comment by storyicon** [comment]
Sorry, after I made some attempts, I can't reproduce this error on Linux and Windows. 
If you are willing to provide more information, I will try more. 
I will keep this issue open for a while to see if anyone else is experiencing the same problem.

**Comment by storyicon** [comment]
I suddenly remembered something.
If you get this error when running `gitlab-ci`, I have also encountered this, it is caused by incorrect configuration of gitlab, you can get some help by modifying these two places:
![image](https://user-images.githubusercontent.com/29772821/59828460-a75b2f00-936d-11e9-8d57-97c188a7228d.png)
![image](https://user-images.githubusercontent.com/29772821/59828874-87783b00-936e-11e9-9305-f51710ecd8f6.png)

**Comment by storyicon** [comment]
When using golang `under` version `1.12`, the following errors may occur when pulling out repositories that are not managed by `go module`: 
```
go: cannot find main module; see'Go help modules', 
```
so use golang `at` or `above` `1.12` to ensure the normal operation of `go module`.
